smart_health_dw:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'postgres') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'de_admin') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'de_admin_secure_pass_2026') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'smart_health_dw') }}"
      schema: gold
      threads: 4
      keepalives_idle: 0
